"""
Built-in fallback abbreviations for offline/CI use.

Contains the ~280 hand-curated clinical abbreviations (from Stedman's,
JCAHO "Do Not Use" list, and common EHR patterns) used when the
Meta-Inventory dataset cannot be downloaded.

In production, the ShorthandExpander loads the full 104K-abbreviation
Meta-Inventory from Zenodo. This fallback is only used when that download
fails or when explicitly requested.
"""

# --- General clinical abbreviations ---
GENERAL = {
    "pt": "patient",
    "pts": "patients",
    "px": "physical examination",
    "hx": "history",
    "pmh": "past medical history",
    "pmhx": "past medical history",
    "fhx": "family history",
    "shx": "social history",
    "h/o": "history of",
    "s/p": "status post",
    "c/o": "complaining of",
    "r/o": "rule out",
    "f/u": "follow up",
    "w/u": "workup",
    "y/o": "year old",
    "yo": "year old",
    "m/f": "male/female",
    "wt": "weight",
    "ht": "height",
    "bmi": "body mass index",
    "cc": "chief complaint",
    "ros": "review of systems",
    "hpi": "history of present illness",
    "dob": "date of birth",
    "a&o": "alert and oriented",
    "a/o": "alert and oriented",
    "wdwn": "well developed well nourished",
    "wd/wn": "well developed well nourished",
    "nad": "no acute distress",
    "nka": "no known allergies",
    "nkda": "no known drug allergies",
    "nkma": "no known medication allergies",
    "wnl": "within normal limits",
    "aox3": "alert and oriented x3",
    "aox4": "alert and oriented x4",
    "aaox3": "awake alert and oriented x3",
    "aaox4": "awake alert and oriented x4",
    "adl": "activities of daily living",
    "adls": "activities of daily living",
    "dme": "durable medical equipment",
    "snf": "skilled nursing facility",
}

# --- Diagnoses / conditions ---
DIAGNOSES = {
    "dm": "diabetes mellitus",
    "dm1": "type 1 diabetes mellitus",
    "dm2": "type 2 diabetes mellitus",
    "t1dm": "type 1 diabetes mellitus",
    "t2dm": "type 2 diabetes mellitus",
    "iddm": "insulin dependent diabetes mellitus",
    "niddm": "non-insulin dependent diabetes mellitus",
    "htn": "hypertension",
    "chf": "congestive heart failure",
    "cad": "coronary artery disease",
    "mi": "myocardial infarction",
    "ami": "acute myocardial infarction",
    "stemi": "st elevation myocardial infarction",
    "nstemi": "non-st elevation myocardial infarction",
    "afib": "atrial fibrillation",
    "a-fib": "atrial fibrillation",
    "aflutter": "atrial flutter",
    "svt": "supraventricular tachycardia",
    "vtach": "ventricular tachycardia",
    "vfib": "ventricular fibrillation",
    "dvt": "deep vein thrombosis",
    "pe": "pulmonary embolism",
    "copd": "chronic obstructive pulmonary disease",
    "sob": "shortness of breath",
    "doe": "dyspnea on exertion",
    "pna": "pneumonia",
    "uti": "urinary tract infection",
    "uri": "upper respiratory infection",
    "gerd": "gastroesophageal reflux disease",
    "ibs": "irritable bowel syndrome",
    "ibd": "inflammatory bowel disease",
    "uc": "ulcerative colitis",
    "gi": "gastrointestinal",
    "gib": "gastrointestinal bleed",
    "ugib": "upper gastrointestinal bleed",
    "lgib": "lower gastrointestinal bleed",
    "cva": "cerebrovascular accident",
    "tia": "transient ischemic attack",
    "ckd": "chronic kidney disease",
    "esrd": "end stage renal disease",
    "aki": "acute kidney injury",
    "arf": "acute renal failure",
    "crf": "chronic renal failure",
    "bph": "benign prostatic hyperplasia",
    "osa": "obstructive sleep apnea",
    "ra": "rheumatoid arthritis",
    "oa": "osteoarthritis",
    "sle": "systemic lupus erythematosus",
    "ms": "multiple sclerosis",
    "als": "amyotrophic lateral sclerosis",
    "pvd": "peripheral vascular disease",
    "pad": "peripheral arterial disease",
    "hld": "hyperlipidemia",
    "hl": "hyperlipidemia",
    "acs": "acute coronary syndrome",
    "aaa": "abdominal aortic aneurysm",
    "ards": "acute respiratory distress syndrome",
    "dic": "disseminated intravascular coagulation",
    "sbo": "small bowel obstruction",
    "lbo": "large bowel obstruction",
    "etoh": "alcohol",
    "sz": "seizure",
    "ha": "headache",
    "cp": "chest pain",
    "lbp": "low back pain",
    "n/v": "nausea/vomiting",
    "n/v/d": "nausea/vomiting/diarrhea",
    "bka": "below knee amputation",
    "aka": "above knee amputation",
}

# --- Treatment / procedures ---
TREATMENT = {
    "tx": "treatment",
    "rx": "prescription",
    "dx": "diagnosis",
    "ddx": "differential diagnosis",
    "sx": "surgery",
    "surg": "surgery",
    "op": "operation",
    "pre-op": "preoperative",
    "post-op": "postoperative",
    "abx": "antibiotics",
    "ppx": "prophylaxis",
    "dc": "discontinue",
    "d/c": "discharge",
    "dispo": "disposition",
    "cpap": "continuous positive airway pressure",
    "bipap": "bilevel positive airway pressure",
    "ngt": "nasogastric tube",
    "foley": "foley catheter",
    "iv": "intravenous",
    "im": "intramuscular",
    "sq": "subcutaneous",
    "subq": "subcutaneous",
    "po": "by mouth",
    "pr": "per rectum",
    "sl": "sublingual",
    "prn": "as needed",
    "qd": "daily",
    "bid": "twice daily",
    "tid": "three times daily",
    "qid": "four times daily",
    "qhs": "at bedtime",
    "qam": "every morning",
    "qpm": "every evening",
    "qod": "every other day",
    "qwk": "every week",
    "ac": "before meals",
    "pc": "after meals",
    "stat": "immediately",
    "ekg": "electrocardiogram",
    "ecg": "electrocardiogram",
    "echo": "echocardiogram",
    "cbc": "complete blood count",
    "bmp": "basic metabolic panel",
    "cmp": "comprehensive metabolic panel",
    "lfts": "liver function tests",
    "tsh": "thyroid stimulating hormone",
    "ua": "urinalysis",
    "ct": "computed tomography",
    "mri": "magnetic resonance imaging",
    "cxr": "chest x-ray",
    "kub": "kidneys ureters bladder x-ray",
    "us": "ultrasound",
    "cabg": "coronary artery bypass graft",
    "ptca": "percutaneous transluminal coronary angioplasty",
    "pci": "percutaneous coronary intervention",
    "ercp": "endoscopic retrograde cholangiopancreatography",
    "egd": "esophagogastroduodenoscopy",
    "lap": "laparoscopic",
    "lap chole": "laparoscopic cholecystectomy",
    "appy": "appendectomy",
    "cath": "catheterisation",
    "trach": "tracheostomy",
    "intub": "intubation",
    "extub": "extubation",
}

# --- Anatomy / physical exam ---
ANATOMY = {
    "abd": "abdomen",
    "ext": "extremities",
    "bilat": "bilateral",
    "le": "lower extremity",
    "ue": "upper extremity",
    "lle": "left lower extremity",
    "rle": "right lower extremity",
    "lue": "left upper extremity",
    "rue": "right upper extremity",
    "ruq": "right upper quadrant",
    "luq": "left upper quadrant",
    "rlq": "right lower quadrant",
    "llq": "left lower quadrant",
    "cv": "cardiovascular",
    "pulm": "pulmonary",
    "neuro": "neurological",
    "msk": "musculoskeletal",
    "heent": "head eyes ears nose throat",
    "eomi": "extraocular movements intact",
    "perrl": "pupils equal round reactive to light",
    "perrla": "pupils equal round reactive to light and accommodation",
    "rrr": "regular rate and rhythm",
    "ctab": "clear to auscultation bilaterally",
    "cta": "clear to auscultation",
    "ntnd": "nontender nondistended",
    "nt/nd": "nontender nondistended",
    "bs": "bowel sounds",
    "nabs": "normoactive bowel sounds",
    "tms": "tympanic membranes",
    "tm": "tympanic membrane",
    "cn": "cranial nerves",
    "dtr": "deep tendon reflexes",
    "dtrs": "deep tendon reflexes",
    "rom": "range of motion",
}

# --- Lab values / vitals ---
LABS = {
    "hr": "heart rate",
    "bp": "blood pressure",
    "sbp": "systolic blood pressure",
    "dbp": "diastolic blood pressure",
    "rr": "respiratory rate",
    "o2 sat": "oxygen saturation",
    "spo2": "oxygen saturation",
    "temp": "temperature",
    "t": "temperature",
    "wbc": "white blood cell count",
    "hgb": "hemoglobin",
    "hct": "hematocrit",
    "plt": "platelet count",
    "plts": "platelets",
    "cr": "creatinine",
    "bun": "blood urea nitrogen",
    "na": "sodium",
    "k": "potassium",
    "cl": "chloride",
    "hco3": "bicarbonate",
    "co2": "carbon dioxide",
    "ca": "calcium",
    "mg": "magnesium",
    "phos": "phosphorus",
    "ast": "aspartate aminotransferase",
    "alt": "alanine aminotransferase",
    "alp": "alkaline phosphatase",
    "tbili": "total bilirubin",
    "dbili": "direct bilirubin",
    "alb": "albumin",
    "tp": "total protein",
    "pt": "prothrombin time",
    "inr": "international normalized ratio",
    "ptt": "partial thromboplastin time",
    "aptt": "activated partial thromboplastin time",
    "esr": "erythrocyte sedimentation rate",
    "crp": "c-reactive protein",
    "hba1c": "hemoglobin a1c",
    "a1c": "hemoglobin a1c",
    "bnp": "brain natriuretic peptide",
    "trop": "troponin",
    "abg": "arterial blood gas",
    "vbg": "venous blood gas",
    "lytes": "electrolytes",
}


def build_fallback_dictionary():
    """Merge all category dictionaries into one."""
    combined = {}
    combined.update(GENERAL)
    combined.update(DIAGNOSES)
    combined.update(TREATMENT)
    combined.update(ANATOMY)
    combined.update(LABS)
    return combined


FALLBACK_ABBREVIATIONS = build_fallback_dictionary()

# Context-sensitive disambiguation rules for ambiguous abbreviations.
# Format: (abbreviation, preceding_context_regex, expansion)
FALLBACK_CONTEXT_RULES = [
    ("pt", r"(?:check|draw|labs?|coags?|elevated|normal|prolonged|inr)\b", "prothrombin time"),
    ("pt", r".*", "patient"),
    ("ms", r"(?:diagnosed|dx|history|hx|has|with)\b", "multiple sclerosis"),
    ("ca", r"(?:check|draw|labs?|level|low|high|elevated|normal)\b", "calcium"),
    ("ca", r"(?:diagnosed|dx|history|hx|has|with|stage|mets?|metastatic)\b", "cancer"),
]
